### ISSUE TITLE
bug: Not Responsive on Various Devices and Screen Sizes

### ISSUE THREAD

**Issue by AlimurtuzaCodes** [AlimurtuzaCodes/Tic-Tac-Toe#2]
### Current Behavior:
The website is not responsive and does not adapt well to different screen sizes or devices. As a result, the content and layout become distorted or difficult to navigate on smaller screens.

### Expected Behavior:
The website should be fully responsive, providing a seamless and user-friendly experience across various devices and screen sizes. The content and layout should adapt dynamically to ensure optimal readability and usability.

**Comment by abdul-o1** [comment]
assign me
